version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418472117.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t gangwar_finalexam .
      - docker tag gangwar_finalexam:latest 905418472117.dkr.ecr.us-east-1.amazonaws.com/gangwar_finalexam:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 905418472117.dkr.ecr.us-east-1.amazonaws.com/gangwar_finalexam:latest
